version: "3.9"

services:
# docker exec -it oracle-ai-db  sqlplus sys/welcome1@FREE as sysdba
  oracle-ai-db:
    image: container-registry.oracle.com/database/free:latest-lite
    container_name: oracle-ai-db
    ports:
      - "${ORACLE_HOST_PORT:-1521}:1521"
    environment:
      ORACLE_PDB: "${ORACLE_PDB:-FREEPDB1}"
      ORACLE_PWD: "${ORACLE_PWD:-welcome1}"
    volumes:
      # Use local project folder ./oradata as the persistent DB storage
      - "./oradata:/opt/oracle/oradata"
      # Optional: startup scripts directory on host â†’ uncomment and point to your scripts
      # - ./oracle-startup-scripts:/opt/oracle/scripts/startup:ro
      - ./sql:/opt/sql
    restart: unless-stopped
